# Generated by Django 5.0.3 on 2024-03-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemHistoricalPricing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(blank=True, max_length=250, null=True)),
                ('ord_closed_dt', models.DateField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_historical_pricing',
                'managed': True,
            },
        ),
    ]
